[workspace]
resolver = "2"
members = [
    "crates/orion-engine",
    "crates/orion-sdf",
    "crates/orion-shader"
]

[workspace.dependencies]
orion-sdf = {path = "crates/orion-sdf"}

bevy = { version = "0.19.0", default-features = false, features = [
    "shader_format_spirv",
    "bevy_window",
    "bevy_winit",
    "bevy_render",
    "bevy_camera",
    "bevy_asset",
    "bevy_mesh",
    "bevy_input_focus",
    "bevy_log",
    "debug"
] }
ndshape = "0.3.0"
spirv-builder = "=0.10.0-alpha.1"
spirv-std = "=0.10.0-alpha.1"