[workspace]
resolver = "2"
members = [
    "crates/orion-engine",
    "crates/orion-mesh",
    "crates/orion-sdf",
    "crates/orion-shader",
    "crates/orion-voxels"
]

[workspace.dependencies]
orion-sdf = {path = "crates/orion-sdf"}
orion-voxels = {path = "crates/orion-voxels"}
orion-mesh = {path = "crates/orion-mesh"}

bevy = { version = "0.19.0", features = ["default", "shader_format_spirv"] }
bevy_dev_tools = "0.19.0"
ndshape = "0.3.0"
spirv-builder = "=0.10.0-alpha.1"
spirv-std = "=0.10.0-alpha.1"