[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = [
    "-Zshare-generics=y",
    "-Zthreads=0"
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"